"""init table

Revision ID: 0c55aedb96b9
Revises: 40fd2031b493
Create Date: 2026-06-01 00:47:56.661022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '0c55aedb96b9'
down_revision: Union[str, Sequence[str], None] = '40fd2031b493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'document', ['content'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='unique')
    # ### end Alembic commands ###
